---
title: "pkgdown"
output: 
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{pkgdown}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Purpose

Automates the generation and deployment of documentation for the R package using [`pkgdown`](https://pkgdown.r-lib.org/). Supports multi-version documentation and custom tweaks for pharmaverse packages.

Source: [`.github/workflows/pkgdown.yml`](https://github.com/pharmaverse/admiralci/blob/main/.github/workflows/pkgdown.yml)

# Inputs

- `r-version`: The version of R to use. The value is passed to the
[r-lib/setup-r](https://github.com/r-lib/actions/tree/v2/setup-r) action (see
its documentation for permitted values).
  
  *Default:* `release`
- `install-package`: Should the package be installed?
  
  *Default:* `true`
- `skip-multiversion-docs`: Skip creation of multi-version docs.
  
  *Default:* `true` (workflow_dispatch), `false` (workflow_call)
- `insert-tweak-page-hook`: Customizes `pkgdown::tweak_page` to fix rdrr.io links.
  
  *Default:* `true`
- `multiversion-docs-landing-page`: Ref for multiversion docs landing page.
  
  *Default:* `main`
- `latest-tag-alt-name`: Alternate name for 'latest-tag' in multiversion docs.
  
  *Default:* `""`
- `branches-or-tags-to-list`: Regular expression for branches/tags listed under 'Versions' dropdown.
  
  *Default:* `^main$|^devel$|^pre-release$|^latest-tag$|^cran-release$|^develop$|^v([0-9]+\\.)?([0-9]+\\.)?([0-9]+)$`
- `GITHUB_PAT`: GitHub API access token (optional, for downstream ops/rendering).

# Jobs

## pkgdown Job

Generates and deploys documentation.

### Conditions

Executed if the commit message does not contain `[skip docs]`.

### Steps

1. Setup R environment using [`setup_R`](https://github.com/pharmaverse/admiralci/blob/main/.github/actions/setup_R/action.yaml) action, installing `pkgdown`.
3. Optionally add a script to fix `rdrr.io` links for pharmaverse packages if `insert-tweak-page-hook` is `true`.
4. Publish documentation using `pkgdown::deploy_to_branch()`, optionally in a subdirectory for multi-version docs or pull requests.
5. Determine website link for documentation.
6. If triggered by a [`pull_request`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request), comment the website link on the PR.

## Multi-version docs Job

Deploys multi-version documentation.

### Conditions

Executed if `skip-multiversion-docs` is `false` and commit message does not contain `[skip docs]`.

### Steps

1. Checkout repository at `gh-pages` branch.
3. Create and publish multi-version docs using [`r-pkgdown-multiversion`](https://github.com/insightsengineering/r-pkgdown-multiversion) action.

# Triggers

- [`workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)
- [`workflow_call`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_call)
