---
title: "Render README"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Render README}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Purpose

Renders the README from R Markdown (`README.Rmd`) to Markdown (`README.md`) and optionally formats the generated Markdown.  
Source: [`.github/workflows/readme-render.yml`](https://github.com/pharmaverse/admiralci/blob/main/.github/workflows/readme-render.yml)

# Inputs

- `r-version`: The version of R to use.  
  *Default:* `release`.
- `skip-md-formatting`: Skip markdown auto-formatting.  
  *Default:* `false`.

# Jobs

## `render` Job

Renders the README and optionally formats it.

### Steps

1. Get branch names ([tj-actions/branch-names@v8](https://github.com/tj-actions/branch-names)).
2. Checkout repo (PR) ([actions/checkout@v4.2.2](https://github.com/actions/checkout), only for pull requests).
3. Checkout repository ([actions/checkout@v4.2.2](https://github.com/actions/checkout), for other events).
4. Restore cache ([actions/cache@v4](https://github.com/actions/cache)).
5. Run staged dependencies ([insightsengineering/staged-dependencies-action@v1](https://github.com/insightsengineering/staged-dependencies-action)).
6. Install dependencies from DESCRIPTION ([remotes::install_local](https://github.com/r-lib/remotes)).
7. Render README to markdown ([rmarkdown::render](https://github.com/rstudio/rmarkdown)).
8. Install Markdown formatter ([quilicicf/markdown-formatter](https://github.com/quilicicf/markdown-formatter), skipped if `skip-md-formatting` is `true`).
9. Add safe directory and set git user ([git config documentation](https://git-scm.com/docs/git-config)).
10. Commit and push formatted README.md ([git commit](https://git-scm.com/docs/git-commit), [git push](https://git-scm.com/docs/git-push)).

### Conditions

- Steps 2 and 3 are conditional on the event type (`pull_request` or not).
- Step 8 is conditional on `skip-md-formatting` input.

# Triggers

- [`workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)
- [`workflow_call`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_call)

