name: 'Set R environment for admiral CI/CD'
description: 'Sets up an R environment using the r-lib actions.
  Additionally it installs the development versions of upstream dependencies as
  defined in staged_dependencies.yaml.'
inputs:
  r-version:
    description: 'R version to use'
    required: true
    default: 'release'
  http-user-agent:
    required: true
    default: 'default'
  extra-packages:
    description: 'extra packages to install (in addition to the dependencies of
      the package and the remotes and yaml package)\n
      A comma separated list is expected.'
    required: true
    default: ''
  install-package:
    description: Should the package be installed?
    required: false
    default: false
    type: boolean

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ inputs.r-version}}
        http-user-agent: ${{ inputs.http-user-agent }}
    - name: Debug
      run: echo "install-package ${{ input.install-package }}"
    - name: install_it
      if: ${{ input.install-package}}
      run: echo "Install it"
    - name: no_install
      if: ${{ input.install-pacakge == 'false'}}
      run: echo "Don't install it"
    - name: install_equal
      if: ${{ input.install-package == 'true'}}
      run: echo "Install it with ="

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::remotes, any::yaml, ${{ inputs.extra-packages}}
    - name: Install Development Versions of Dependencies
      if: |
        !(contains(github.event.commits[0].message, '[skip vbump]') ||
          contains(github.event.head_commit.message, '[skip vbump]') ||
          github.ref == 'refs/heads/patch'
         )
      run: |
        # Install Development Version of Upstream Dependencies
        if (file.exists("staged_dependencies.yaml")) {
          dev_dependencies <- yaml::read_yaml("staged_dependencies.yaml")$upstream_repos |>
            sapply(function(x) x$repo)
          if (length(dev_dependencies) > 0) {
            # add names for having bullets in message
            names(dev_dependencies) <- rep("*", length(dev_dependencies))
            cli::cli_bullets(c(
              i = "The development versions of the following packages will be installed:",
              dev_dependencies
            ))
            for (i in seq_along(dev_dependencies)) {
              remotes::install_github(dev_dependencies[[i]], ref = "main")
            }
          } else {
            cli::cli_alert_info("No upstream dependencies found in {.file staged_dependencies.yaml}.\n")
          }
        } else {
          cli::cli_alert_warning("No dependency file ({.file staged_dependencies.yaml}) found.\n")
        }
      shell: Rscript {0}
    - name: Install package
      if: ${{ inputs.install-package }}
      run: |
        # Install package
        install.packages("devtools")
        devtools::install()
      shell: Rscript {0}

