name: CRAN Status md5 codes
description: Write CRAN status table as md5 codes

on:
  workflow_call:
    inputs:
      status-types:
        description: |
          Create an issue if one or more of the following
          statuses are reported on the check report.
          This is a comma-separated string of statuses.
          Allowed statuses are 'NOTE', 'WARN', and 'ERROR'
        default: 'ERROR'
        required: false
        type: string

concurrency:
  group: cran-status-hash-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

runs:
  using: 'docker'
  image: './Dockerfile'
  args:
    - ${{ inputs.status-types }}
