---
name: Check URLs

on:
  push:
    branches:
      - main
      - devel
      - pre-release
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
      - devel
      - pre-release
  workflow_dispatch:
  workflow_call:

concurrency:
  group: links-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  links:
    name: Validate Links
    runs-on: ubuntu-20.04
    if: >
      !contains(github.event.commits[0].message, '[skip links]')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check URLs in docs
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          fail: true
          jobSummary: true
          format: markdown
          output: links-results.md
          args: >-
            --exclude-private
            --exclude "https://github.com.*.git|lycheeverse.*"
            --verbose
            --no-progress
            ${{ inputs.additional_args }}
            **/*.md
            **/*.html
            **/*.Rmd
            **/*.yaml
            **/*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
